from renewable_energy_uq import RenewableEnergyUQ
import os
import argparse

#######[For Local Testing]########
"""os.environ["ISDAFNI"] = "True"
os.environ["NO_SAMPLES"] = "1000"
os.environ["START_DATE"] = "2004-12-01"
os.environ["END_DATE"] = "2005-02-28"
os.environ["BUSES_INFRA_FILE"] = "data/inputs/buses.json"
os.environ["WIND_GEN_INFRA_FILE"] = "data/inputs/generators_wind.json"
os.environ["SOLAR_GEN_INFRA_FILE"] = "data/inputs/generators_pv.json"
os.environ["TRANSMISSION_LINES_INFRA_FILE"] = "data/inputs/lines.json"
os.environ["CITY_NAME_MAPPING_FILE"] = "data/inputs/city_fname_to_name.json"
os.environ["TEMPERATURE_DATA"] = "data/inputs/surface_temperature.zip"
os.environ["WIND_SPEED_DATA"] = "data/inputs/surface_wind_speed.zip"
os.environ["SOLAR_DATA"] = "data/inputs/surface_shortwave_radiation.zip""""
##################################

#If DAFNI
isDAFNI = os.environ.get("ISDAFNI")

gDEBUG = False

# Pre-amble to setup folders
print("ISDAFNI Environment variable = ", isDAFNI, type(isDAFNI))
if isDAFNI == "True":
    if os.name == "nt":
        pren = os.environ.get("HOMEDRIVE")
    else:
        pren = "/"
    gPATHI = os.path.join(pren, "data", "inputs")
    gPATHO = os.path.join(pren, "data", "outputs")


    print("Running within DAFNI: ", gPATHO)
else:
    print("Not running within DAFNI, using run directory")

class Inputs():

    def __init__(self, ArgObj=None):
        if ArgObj == None:
            # No ArgParser, use environments (ie. running in DAFNI)
            self.no_samples = int( os.environ.get("NO_SAMPLES") )
            self.start_date = os.environ.get("START_DATE")
            self.end_date = os.environ.get("END_DATE")

            self.data_fpaths = {
                "buses":  os.environ.get("BUSES_INFRA_FILE", ""),
                "wind_generators": os.environ.get("WIND_GEN_INFRA_FILE", ""),                
                "solar_generators": os.environ.get("SOLAR_GEN_INFRA_FILE", ""),
                "transmission_lines": os.environ.get("TRANSMISSION_LINES_INFRA_FILE", ""),
                "city_name_mapping": os.environ.get("CITY_NAME_MAPPING_FILE", ""),
                "temperature_data": os.environ.get("TEMPERATURE_DATA", "").split(","),
                "wind_speed_data": os.environ.get("WIND_SPEED_DATA", "").split(","),
                "solar_data": os.environ.get("SOLAR_DATA", "").split(","),
                "input_path": gPATHI
            }

        else:
            self.no_samples = ArgObj.no_samples
            self.start_date = ArgObj.start_date
            self.end_date = ArgObj.end_date

            # TBD: Not fully understood, generated by ChatGPT
            self.data_fpaths = {
                "buses": ArgObj.buses_file if hasattr(ArgObj, "buses_file") else "",
                "wind_generators": ArgObj.wind_gen_file if hasattr(ArgObj, "wind_gen_file") else "",
                "solar_generators": ArgObj.solar_gen_file if hasattr(ArgObj, "solar_gen_file") else "",
                "transmission_lines": ArgObj.transmission_lines_file if hasattr(ArgObj, "transmission_lines_file") else "",
                "city_name_mapping": ArgObj.city_name_mapping_file if hasattr(ArgObj, "city_name_mapping_file") else "",
                "temperature_data": ArgObj.temperature_data.split(",") if hasattr(ArgObj, "temperature_data") else [],
                "wind_speed_data": ArgObj.wind_speed_data.split(",") if hasattr(ArgObj, "wind_speed_data") else [],
                "solar_data": ArgObj.solar_data.split(",") if hasattr(ArgObj, "solar_data") else [],
            }

def main():
    if isDAFNI == "True":
        # Running in DAFNI, use the environment variables
        inputs = Inputs()
    else:
        # Running locally, use the command line arguments
        parser = argparse.ArgumentParser()
        parser.add_argument("--no_samples", type=int, default=1000)
        parser.add_argument("--start_date", type=str, default="2004-12-01")
        parser.add_argument("--end_date", type=str, default="2005-02-28")
        parser.add_argument("--buses_file", type=str, default="")
        parser.add_argument("--wind_gen_file", type=str, default="")
        parser.add_argument("--solar_gen_file", type=str, default="")
        parser.add_argument("--transmission_lines_file", type=str, default="")
        parser.add_argument("--city_name_mapping_file", type=str, default="")
        parser.add_argument("--temperature_data", type=str, default="")
        parser.add_argument("--wind_speed_data", type=str, default="")
        parser.add_argument("--solar_data", type=str, default="")
        inputs = Inputs(parser.parse_args())

    analysis = RenewableEnergyUQ(inputs.data_fpaths, inputs.start_date, inputs.end_date, gPATHI, gPATHO)
    
    sampled_temp_df = analysis.sample_temperature(inputs.no_samples)
    sampled_temp_df.to_parquet(
        os.path.join(gPATHO, "temperature_samples.parquet"),
        engine="pyarrow"
    )
    
    sampled_wind_df = analysis.sample_wind_speed(inputs.no_samples)
    sampled_wind_df.to_parquet(
        os.path.join(gPATHO, "wind_speed_samples.parquet"),
        engine="pyarrow"
    )

    sampled_solar_df = analysis.sample_solar_radiation(inputs.no_samples)
    sampled_solar_df.to_parquet(
        os.path.join(gPATHO, "solar_radiation_samples.parquet"),
        engine="pyarrow"
    )

    sampled_demand_df = analysis.sample_net_demand(sampled_temp_df)
    sampled_demand_df.to_parquet(
        os.path.join(gPATHO, "demand_samples.parquet"),
        engine="pyarrow"
    )

    optimisation_results = analysis.optimise_energy_system(sampled_wind_df, sampled_solar_df, sampled_demand_df)
    loadshed_path = os.path.join(gPATHO, "loadshed.parquet")
    analysis.save_loadshed_as_parquet(optimisation_results, loadshed_path)

    #analysis.plot_histogram(loadshed_path, f"loadshed_hist.png", column_name="total")

if __name__ == "__main__":
    main()